### ISSUE TITLE
tasty test fails in Stackage Nightly build

### ISSUE THREAD

**Issue by juhp** [wincent/docvim#25]
I haven't tried locally yet but when trying to run the tasty test in Stackage Nightly for docvim-0.3.1.1:

```
> /tmp/stackage-build8/docvim-0.3.1.1$ dist/build/tasty/tasty
tasty: tests/fixtures/parser: getDirectoryContents: does not exist (No such file or directory)
```

**Comment by wincent** [comment]
Passes locally for me but I'll see if I can figure out why it might fail in Stackage. Thanks for letting me know.

**Comment by juhp** [comment]
I can reproduce with:

```
$ cabal get docvim-0.3.1.1
$ cd docvim-0.3.1.1
$ stack --resolver nightly init
$ stack test
```

I wish `stack --resolver nightly test docvim` would work.

**Comment by wincent** [comment]
Having added the missing fixture files, looks like it works now:

```
cabal update
cabal get docvim-0.3.1.2
cd docvim-0.3.1.2
stack --resolver nightly init
stack test
```

([Full transcript](https://gist.github.com/wincent/82ad8b0ff4cce9ebc824656d9a0479fd)).
